using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fibonacci
{

//    Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


    class Program
    {
        static void Main(string[] args)
        {
            //calculate sum of the fibonacci series until last item smaller than input value
            int f1 = 0, f2 = 1, f3 = 0;
            int sumOfSeries = 0;

            Console.WriteLine("Please input a number which will be bigger than serie's last item");
            //according to problem it should be 4million
            long limit = Convert.ToInt32(Console.ReadLine());

            while (f3<limit)
            {
                f3 = f1 + f2;
                if (f3 > limit) break;
                Console.WriteLine(f3);
                if (f3 %2 ==0)
                {
                    sumOfSeries = sumOfSeries + f3;
                }                

                f1 = f2;
                f2 = f3;
            }
            Console.WriteLine("Sum of above serie is : {0}", sumOfSeries);
            Console.ReadLine();

        }

    }
}
